import { Router } from "express";
// import activityLogsRoutes from "../modules/activity-logs/activity-logs.routes.js";
// import attachmentsRoutes from "../modules/attachments/attachments.routes.js";
// import labelsRoutes from "../modules/labels/labels.routes.js";
// import notificationRoutes from "../modules/notification/notification.routes.js";
// import notificationTypeRoutes from "../modules/notification-type/notification-type.routes.js";
// import organizationMembersRoutes from "../modules/organization-members/organization-members.routes.js";
// import organizationRoutes from "../modules/organizations/organizations.routes.js";
// import priorityRoutes from "../modules/priority/priority.routes.js";
// import projectMembersRoutes from "../modules/project-members/project-members.routes.js";
// import projectsRoutes from "../modules/projects/projects.routes.js";
// import roleRoutes from "../modules/role/role.routes.js";
// import statusRoutes from "../modules/status/status.routes.js";
// import taskCommentsRoutes from "../modules/task-comments/task-comments.routes.js";
// import taskHistoryRoutes from "../modules/task-history/task-history.routes.js";
// import taskLabelsRoutes from "../modules/task-labels/task-labels.routes.js";
// import tasksRoutes from "../modules/tasks/tasks.routes.js";
// import taskWatchersRoutes from "../modules/task-watchers/task-watchers.routes.js";
import userRoutes from "../modules/users/user.routes.js";

const router = Router();

// router.use("/activity-logs", activityLogsRoutes);
// router.use("/attachments", attachmentsRoutes);
// router.use("/labels", labelsRoutes);
// router.use("/notification", notificationRoutes);
// router.use("/notification-type", notificationTypeRoutes);
// router.use("/organization-members", organizationMembersRoutes);
// router.use("/organizations", organizationRoutes);
// router.use("/priority", priorityRoutes);
// router.use("/project-members", projectMembersRoutes);
// router.use("/projects", projectsRoutes);
// router.use("/role", roleRoutes);
// router.use("/status", statusRoutes);
// router.use("/task-comments", taskCommentsRoutes);
// router.use("/task-history", taskHistoryRoutes);
// router.use("/task-labels", taskLabelsRoutes);
// router.use("/tasks", tasksRoutes);
// router.use("/task-watchers", taskWatchersRoutes);
router.use("/users", userRoutes);

export default router;